### ISSUE TITLE
Markdown형식 firebase에 저장

### ISSUE THREAD

**Issue by thereisname** [thereisname/TravelDiaryProject#10]
게시물 작성 후 firebase에 저장하는 과정에서 게시물 작성은 markdown형태로 변형됨.
markdown에서 여러장의 image를 걸러내 저장하는 방식 고안 필요.

게시물 자체도 markdown이라 이 형태 그대로 저장 시 불러올 때 문제가 발생할 가능성이 있음.

**Comment by wjdsheep15** [comment]
https://yoon-dailylife.tistory.com/109
https://developer.android.com/training/printing/html-docs?hl=ko
https://black-jin0427.tistory.com/272

**Comment by thereisname** [comment]
Html.fromHtml()
